name: lotify
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  image_picker: ^1.0.4
  video_player: ^2.7.2
  http: ^0.13.6
  http_parser: ^4.0.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router: ^13.1.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2
  http: ^0.13.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "lotify"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21